# Generated by Django 4.1.5 on 2023-01-27 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('genero', models.CharField(choices=[('romance', 'Romance'), ('aventura', 'Aventura'), ('autoajuda', 'Auto Ajuda'), ('infantil', 'Infantil'), ('ficcao', 'Ficção'), ('quadrinho', 'História em quadrinho'), ('religiao', 'Religião'), ('terror', 'Terror')], max_length=30)),
                ('editora', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('data_publicacao', models.IntegerField(blank=True, max_length=4)),
                ('qtd_paginas', models.IntegerField()),
            ],
        ),
    ]
