# Generated by Django 4.1.5 on 2023-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='nome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_publicacao',
            field=models.IntegerField(blank=True),
        ),
    ]
