# Generated by Django 4.1.5 on 2023-01-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_livros_nome_alter_livros_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_publicacao',
            field=models.DateField(blank=True),
        ),
    ]
